-- 코드를 입력하세요

-- 식품 정보: FOOD_PRODUCT
    -- PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
    -- 식품 ID, 식품 이름, 식품코드, 식품분류, 식품 가격
-- 주문 정보: FOOD_ORDER
    -- ORDER_ID, PRODUCT_ID, AMOUNT, PRODUCE_DATE, IN_DATE, OUT_DATE, FACTORY_ID, WAREHOUSE_ID
    -- 주문 ID, 제품 ID, 주문량, 생산일자, 입고일자, 출고일자, 공장 ID, 창고 ID
    
-- 출력: PRODUCE_DATE = '2022-05%',
-- 총매출을 기준으로 DESC, 
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN FOOD_ORDER o
    ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE LIKE '2022-05%'
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID
