-- 코드를 입력하세요

--  2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차


SELECT MONTH(START_DATE) AS MONTH, 
    CAR_ID, 
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= "2022-08-01" AND 
        START_DATE <= "2022-10-31"
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
) AND START_DATE >= "2022-08-01" AND 
        START_DATE <= "2022-10-31"
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC