-- 코드를 입력하세요
-- 대여 시작일: 2022-08 ~ 2022-10까지 5회 이상 대여

WITH cars AS (SELECT CAR_ID
             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
             WHERE MONTH(START_DATE) BETWEEN 8 AND 10
             GROUP BY CAR_ID
                HAVING COUNT(*) >= 5)
             
SELECT MONTH(h.START_DATE) AS MONTH, h.CAR_ID, COUNT(h.CAR_ID) AS RECORDS
FROM cars c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    ON c.CAR_ID = h.CAR_ID
WHERE MONTH(h.START_DATE) BETWEEN 8 AND 10
GROUP BY MONTH, h.CAR_ID
ORDER BY MONTH, h.CAR_ID DESC