-- 코드를 입력하세요
-- 년, 월, 성별 별로 상품을 구매한 회원수를 집계
-- 회원수는 DISTINCT로 해야함 (동일한 년월에 구매할 수 도 있으니까 - 한명으로 취급)
-- 성별이 NULL이면 제외


SELECT YEAR(s.SALES_DATE) AS YEAR, MONTH(s.SALES_DATE) AS MONTH, 
    i.GENDER, COUNT(DISTINCT i.USER_ID) AS USERS
FROM USER_INFO i
JOIN ONLINE_SALE s
    ON i.USER_ID = s.USER_ID
WHERE i.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, i.GENDER
ORDER BY YEAR, MONTH, i.GENDER