-- 코드를 입력하세요
-- 대여중 정보:CAR_RENTAL_COMPANY_CAR
    -- CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS
    -- 자동차 ID, 자동차 종류, 일일 대여 요금(원), 자동차 옵션 리스트
-- 대여 기록: CAR_RENTAL_COMPANY_RENTAL_HISTORY
    -- HISTORY_ID, CAR_ID, START_DATE, END_DATE
    -- 자동차 대여 기록 ID, 자동차 ID, 대여 시작일, 대여 종료일
-- 할인 정책: CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    -- PLAN_ID, CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
    -- 요금 할인 정책 ID, 자동차 종류, 대여 기간 종류, 할인율(%)

SELECT c.CAR_ID, c.CAR_TYPE, ROUND((c.DAILY_FEE * (100-p.DISCOUNT_RATE) * 30 / 100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
    ON c.CAR_TYPE = p.CAR_TYPE
WHERE (c.CAR_TYPE = '세단' OR c.CAR_TYPE = 'SUV')
AND p.DURATION_TYPE = '30일 이상'
AND c.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30'
    AND END_DATE >= '2022-11-01'
)
AND ((c.DAILY_FEE * (100-p.DISCOUNT_RATE)* 30 / 100) BETWEEN 500000 AND 2000000)
ORDER BY FEE DESC, c.CAR_TYPE, c.CAR_ID DESC