-- 코드를 입력하세요
-- 입양 보낸 정보: ANIMAL_OUTS

WITH RECURSIVE hours AS (
    SELECT 0 AS H
    UNION ALL
    SELECT H+1 FROM hours WHERE H < 23
)

SELECT 
    h.H AS HOUR,
    COUNT(a.DATETIME) AS COUNT
FROM hours h
LEFT JOIN ANIMAL_OUTS a
    ON h.H = HOUR(a.DATETIME)
GROUP BY h.H
ORDER BY h.H