-- 코드를 입력하세요

-- 출력: 아직 입양을 못간애(보호소 - 입양), DATETIME (LIMIT 3)
-- NAME, DATETIME

SELECT NAME, DATETIME
FROM ANIMAL_INS i
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID
                       FROM ANIMAL_OUTS)
ORDER BY DATETIME
LIMIT 3