-- 코드를 입력하세요
-- 상품 정보: PRODUCT
    --  PRODUCT_ID, PRODUCT_CODE, PRICE
-- 오프라인: OFFLINE_SALE
    -- OFFLINE_SALE_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    
-- 출력: 상품별 매출액(판매가*판매랑)합계
-- 매출액 기준 오름차순

SELECT p.PRODUCT_CODE, SUM(p.PRICE * o.SALES_AMOUNT) AS SALES
FROM PRODUCT p
JOIN OFFLINE_SALE o
    ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, p.PRODUCT_CODE
