-- 코드를 입력하세요
-- 대여 정보: CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    -- HISTORY_ID, CAR_ID, START_DATE, END_DATE
    -- 대여 기록 ID, 자동차 ID, 대여 시작일, 대여 종료일
    
-- CAR_ID의 그룹별로, END_DATE의 최대값 뽑기
SELECT DISTINCT CAR_ID,
    IF (CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE),
       '대여중',
       '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC;