-- 코드를 입력하세요

-- 가격 * 판매량

WITH total AS (SELECT b.BOOK_ID, b.CATEGORY, b.AUTHOR_ID, b.PRICE, s.SALES_DATE, s.SALES
FROM BOOK b
JOIN BOOK_SALES s
    ON b.BOOK_ID = s.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%')

SELECT t.AUTHOR_ID, a.AUTHOR_NAME, t.CATEGORY, SUM(t.PRICE * t.SALES) AS TOTAL_SALES
FROM total t
JOIN AUTHOR a
    ON t.AUTHOR_ID = a.AUTHOR_ID
GROUP BY t.AUTHOR_ID, t.CATEGORY
ORDER BY t.AUTHOR_ID, t.CATEGORY DESC
