-- 코드를 입력하세요
-- 식품 정보: FOOD_PRODUCT
    -- PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE: 
    -- 식품 ID, 식품 이름, 식품 코드, 식품분류, 식품 가격
    
-- 출력: 가격이 제일 비싼

SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);
