-- 코드를 입력하세요
-- 회원 정보: MEMBER_PROFILE
    -- 속성: MEMBER_ID, MEMBER_NAME(이름), TLNO, GENDER, DATE_OF_BIRTH
    
-- 출력: DATE_OF_BIRTH == 3월 AND 
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL
    AND GENDER = 'W'
    AND DATE_OF_BIRTH LIKE '%-03-%'
ORDER BY MEMBER_ID;