-- 코드를 입력하세요
WITH duration AS (SELECT HISTORY_ID, CAR_ID,
                    (DATEDIFF(END_DATE, START_DATE) + 1) AS DAYS
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) 
    
SELECT CAR_ID, ROUND(AVG(DAYS), 1) AS AVERAGE_DURATION
FROM duration
GROUP BY CAR_ID
HAVING AVG(DAYS) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
