WITH day AS (
    SELECT 
        c.CAR_ID,
        c.CAR_TYPE,
        h.HISTORY_ID,
        c.DAILY_FEE,
        CASE
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE '7일 미만'
        END AS DAY
    FROM CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
        ON c.CAR_ID = h.CAR_ID
    WHERE c.CAR_TYPE = '트럭'
)

SELECT 
    d.HISTORY_ID,
    ROUND(
        CASE 
            WHEN d.DAY = '7일 미만' THEN d.DAILY_FEE * (DATEDIFF((SELECT END_DATE FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h2 WHERE h2.HISTORY_ID = d.HISTORY_ID), (SELECT START_DATE FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h2 WHERE h2.HISTORY_ID = d.HISTORY_ID)) + 1)
            ELSE d.DAILY_FEE * (DATEDIFF((SELECT END_DATE FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h2 WHERE h2.HISTORY_ID = d.HISTORY_ID), (SELECT START_DATE FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h2 WHERE h2.HISTORY_ID = d.HISTORY_ID)) + 1) * (100 - p.DISCOUNT_RATE) / 100
        END
    , 0) AS FEE
FROM day d
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
    ON d.CAR_TYPE = p.CAR_TYPE
   AND d.DAY = p.DURATION_TYPE
ORDER BY FEE DESC, d.HISTORY_ID DESC;
