-- 코드를 입력하세요
-- 2022년 1월의 카테고리별 도서 판매량 합산

SELECT b.CATEGORY, SUM(s.SALES) AS TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES s
    ON b.BOOK_ID = s.BOOK_ID
WHERE s.SALES_DATE LIKE '2022-01%'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY
