-- 코드를 입력하세요
-- 음식 종류별, 즐겨찾기가 가장 많은 식당의 정보

WITH max_f AS (SELECT MAX(FAVORITES) AS MAX_FAVORITES, FOOD_TYPE
                  FROM REST_INFO
                  GROUP BY FOOD_TYPE)
SELECT m.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM max_f m
JOIN REST_INFO r
    ON m.MAX_FAVORITES = r.FAVORITES
    AND m.FOOD_TYPE = r.FOOD_TYPE
ORDER BY m.FOOD_TYPE DESC