-- 코드를 입력하세요
SELECT i.ANIMAL_ID, i.NAME
FROM ANIMAL_INS i
RIGHT JOIN ANIMAL_OUTS o
    ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE i.DATETIME IS NOT NULL
ORDER BY DATEDIFF(o.DATETIME, i.DATETIME)+1 DESC
LIMIT 2
    